import type { Metadata } from 'next';
import './index.css';

import { QueryClientProvider } from '@/provider/QueryClientProvider';
import { FilterBar } from '../features/filter';
import { TabMenu } from '../features/menu';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProvider>
        <body>
          <FilterBar />
          {children}
          <TabMenu />
        </body>
      </QueryClientProvider>
    </html>
  );
}
