import { ReactNode } from 'react';
import type { Metadata } from 'next';
import './index.css';

import { Providers } from '@/provider';
import { FilterBar } from '../features/filter';
import { TabMenu } from '../features/menu';

interface RootLayoutProps {
  children: ReactNode;
  modal: ReactNode;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <FilterBar />
          {children}
          <TabMenu />

          {modal}
        </body>
      </Providers>
    </html>
  );
}
